version: '2'
services:
    mc437-postgresql:
        container_name: mc437-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/mc437/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=mc437
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
